[package]
name = "dummy-rcon-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dotenv = "0.15.0"
env_logger = "0.11.5"
log = "0.4.22"
thiserror = "2.0.0"
tokio = { version = "1.41.1", features = ["full"] }
